# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Cgtriangle(object):
    def setupUi(self, Cgtriangle):
        Cgtriangle.setObjectName("Cgtriangle")
        Cgtriangle.resize(1024, 415)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Cgtriangle.sizePolicy().hasHeightForWidth())
        Cgtriangle.setSizePolicy(sizePolicy)
        Cgtriangle.setMinimumSize(QtCore.QSize(1024, 415))
        Cgtriangle.setMaximumSize(QtCore.QSize(1024, 415))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Cgtriangle.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Cgtriangle)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 361, 374))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_vertices = QtWidgets.QWidget()
        self.tab_vertices.setObjectName("tab_vertices")
        self.pushVertice = QtWidgets.QPushButton(self.tab_vertices)
        self.pushVertice.setGeometry(QtCore.QRect(290, 312, 61, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushVertice.setIcon(icon1)
        self.pushVertice.setCheckable(False)
        self.pushVertice.setFlat(False)
        self.pushVertice.setObjectName("pushVertice")
        self.popVertice = QtWidgets.QPushButton(self.tab_vertices)
        self.popVertice.setGeometry(QtCore.QRect(225, 312, 61, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.popVertice.setIcon(icon2)
        self.popVertice.setCheckable(False)
        self.popVertice.setFlat(False)
        self.popVertice.setObjectName("popVertice")
        self.tableVertices = QtWidgets.QTableView(self.tab_vertices)
        self.tableVertices.setGeometry(QtCore.QRect(-1, -1, 361, 351))
        self.tableVertices.setObjectName("tableVertices")
        self.helpText = QtWidgets.QTextEdit(self.tab_vertices)
        self.helpText.setEnabled(True)
        self.helpText.setGeometry(QtCore.QRect(20, 90, 311, 141))
        self.helpText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.helpText.setReadOnly(True)
        self.helpText.setObjectName("helpText")
        self.tableVertices.raise_()
        self.popVertice.raise_()
        self.pushVertice.raise_()
        self.helpText.raise_()
        self.tabWidget.addTab(self.tab_vertices, "")
        self.tab_transformations = QtWidgets.QWidget()
        self.tab_transformations.setStyleSheet("")
        self.tab_transformations.setObjectName("tab_transformations")
        self.boxTranslation = QtWidgets.QGroupBox(self.tab_transformations)
        self.boxTranslation.setEnabled(True)
        self.boxTranslation.setGeometry(QtCore.QRect(10, 10, 161, 95))
        self.boxTranslation.setStyleSheet("")
        self.boxTranslation.setFlat(False)
        self.boxTranslation.setCheckable(True)
        self.boxTranslation.setChecked(False)
        self.boxTranslation.setObjectName("boxTranslation")
        self.translation_tx = QtWidgets.QDoubleSpinBox(self.boxTranslation)
        self.translation_tx.setGeometry(QtCore.QRect(70, 30, 81, 26))
        self.translation_tx.setWrapping(False)
        self.translation_tx.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.translation_tx.setDecimals(2)
        self.translation_tx.setMinimum(-100.0)
        self.translation_tx.setMaximum(100.0)
        self.translation_tx.setObjectName("translation_tx")
        self.translation_ty = QtWidgets.QDoubleSpinBox(self.boxTranslation)
        self.translation_ty.setGeometry(QtCore.QRect(70, 60, 81, 26))
        self.translation_ty.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.translation_ty.setMinimum(-100.0)
        self.translation_ty.setMaximum(100.0)
        self.translation_ty.setObjectName("translation_ty")
        self.label = QtWidgets.QLabel(self.boxTranslation)
        self.label.setGeometry(QtCore.QRect(40, 30, 21, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.boxTranslation)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 21, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.boxScale = QtWidgets.QGroupBox(self.tab_transformations)
        self.boxScale.setEnabled(True)
        self.boxScale.setGeometry(QtCore.QRect(10, 110, 161, 121))
        self.boxScale.setStyleSheet("")
        self.boxScale.setFlat(False)
        self.boxScale.setCheckable(True)
        self.boxScale.setChecked(False)
        self.boxScale.setObjectName("boxScale")
        self.scale_sx = QtWidgets.QDoubleSpinBox(self.boxScale)
        self.scale_sx.setGeometry(QtCore.QRect(70, 30, 81, 26))
        self.scale_sx.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.scale_sx.setMinimum(-100.0)
        self.scale_sx.setMaximum(100.0)
        self.scale_sx.setObjectName("scale_sx")
        self.scale_sy = QtWidgets.QDoubleSpinBox(self.boxScale)
        self.scale_sy.setGeometry(QtCore.QRect(70, 60, 81, 26))
        self.scale_sy.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.scale_sy.setMinimum(-100.0)
        self.scale_sy.setMaximum(100.0)
        self.scale_sy.setObjectName("scale_sy")
        self.label_3 = QtWidgets.QLabel(self.boxScale)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 21, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.boxScale)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 21, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.boxScale)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 51, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.scale_point = QtWidgets.QComboBox(self.boxScale)
        self.scale_point.setEnabled(False)
        self.scale_point.setGeometry(QtCore.QRect(70, 90, 81, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_point.sizePolicy().hasHeightForWidth())
        self.scale_point.setSizePolicy(sizePolicy)
        self.scale_point.setMinimumSize(QtCore.QSize(81, 25))
        self.scale_point.setMaximumSize(QtCore.QSize(81, 25))
        self.scale_point.setEditable(False)
        self.scale_point.setObjectName("scale_point")
        self.boxShearing = QtWidgets.QGroupBox(self.tab_transformations)
        self.boxShearing.setEnabled(True)
        self.boxShearing.setGeometry(QtCore.QRect(180, 10, 161, 95))
        self.boxShearing.setStyleSheet("")
        self.boxShearing.setFlat(False)
        self.boxShearing.setCheckable(True)
        self.boxShearing.setChecked(False)
        self.boxShearing.setObjectName("boxShearing")
        self.shear_cx = QtWidgets.QDoubleSpinBox(self.boxShearing)
        self.shear_cx.setGeometry(QtCore.QRect(70, 30, 81, 26))
        self.shear_cx.setWrapping(False)
        self.shear_cx.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.shear_cx.setDecimals(2)
        self.shear_cx.setMinimum(-100.0)
        self.shear_cx.setMaximum(100.0)
        self.shear_cx.setObjectName("shear_cx")
        self.shear_cy = QtWidgets.QDoubleSpinBox(self.boxShearing)
        self.shear_cy.setGeometry(QtCore.QRect(70, 60, 81, 26))
        self.shear_cy.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.shear_cy.setMinimum(-100.0)
        self.shear_cy.setMaximum(100.0)
        self.shear_cy.setObjectName("shear_cy")
        self.label_6 = QtWidgets.QLabel(self.boxShearing)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 21, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.boxShearing)
        self.label_7.setGeometry(QtCore.QRect(40, 60, 21, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.boxRotation = QtWidgets.QGroupBox(self.tab_transformations)
        self.boxRotation.setEnabled(True)
        self.boxRotation.setGeometry(QtCore.QRect(180, 110, 161, 121))
        self.boxRotation.setStyleSheet("")
        self.boxRotation.setFlat(False)
        self.boxRotation.setCheckable(True)
        self.boxRotation.setChecked(False)
        self.boxRotation.setObjectName("boxRotation")
        self.label_10 = QtWidgets.QLabel(self.boxRotation)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 41, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.boxRotation)
        self.label_12.setGeometry(QtCore.QRect(10, 90, 51, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.rotation_vertices = QtWidgets.QComboBox(self.boxRotation)
        self.rotation_vertices.setEnabled(False)
        self.rotation_vertices.setGeometry(QtCore.QRect(70, 90, 81, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotation_vertices.sizePolicy().hasHeightForWidth())
        self.rotation_vertices.setSizePolicy(sizePolicy)
        self.rotation_vertices.setMinimumSize(QtCore.QSize(81, 25))
        self.rotation_vertices.setMaximumSize(QtCore.QSize(81, 25))
        self.rotation_vertices.setEditable(False)
        self.rotation_vertices.setObjectName("rotation_vertices")
        self.rotation_direction = QtWidgets.QComboBox(self.boxRotation)
        self.rotation_direction.setEnabled(False)
        self.rotation_direction.setGeometry(QtCore.QRect(70, 60, 81, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotation_direction.sizePolicy().hasHeightForWidth())
        self.rotation_direction.setSizePolicy(sizePolicy)
        self.rotation_direction.setMinimumSize(QtCore.QSize(81, 25))
        self.rotation_direction.setMaximumSize(QtCore.QSize(81, 25))
        self.rotation_direction.setEditable(False)
        self.rotation_direction.setObjectName("rotation_direction")
        self.label_13 = QtWidgets.QLabel(self.boxRotation)
        self.label_13.setGeometry(QtCore.QRect(0, 60, 61, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.rotation_angle = QtWidgets.QSpinBox(self.boxRotation)
        self.rotation_angle.setGeometry(QtCore.QRect(70, 30, 81, 26))
        self.rotation_angle.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.rotation_angle.setSpecialValueText("")
        self.rotation_angle.setProperty("showGroupSeparator", False)
        self.rotation_angle.setMinimum(0)
        self.rotation_angle.setMaximum(360)
        self.rotation_angle.setSingleStep(45)
        self.rotation_angle.setObjectName("rotation_angle")
        self.boxReflection = QtWidgets.QGroupBox(self.tab_transformations)
        self.boxReflection.setEnabled(True)
        self.boxReflection.setGeometry(QtCore.QRect(10, 237, 151, 95))
        self.boxReflection.setStyleSheet("")
        self.boxReflection.setFlat(False)
        self.boxReflection.setCheckable(True)
        self.boxReflection.setChecked(False)
        self.boxReflection.setObjectName("boxReflection")
        self.reflection_x = QtWidgets.QCheckBox(self.boxReflection)
        self.reflection_x.setGeometry(QtCore.QRect(70, 47, 31, 23))
        self.reflection_x.setObjectName("reflection_x")
        self.reflection_y = QtWidgets.QCheckBox(self.boxReflection)
        self.reflection_y.setGeometry(QtCore.QRect(110, 47, 31, 23))
        self.reflection_y.setObjectName("reflection_y")
        self.label_11 = QtWidgets.QLabel(self.boxReflection)
        self.label_11.setGeometry(QtCore.QRect(30, 47, 31, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_transformations, "")
        self.outputFrame = QtWidgets.QFrame(self.centralwidget)
        self.outputFrame.setGeometry(QtCore.QRect(380, 37, 634, 346))
        self.outputFrame.setStyleSheet("background:white")
        self.outputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputFrame.setObjectName("outputFrame")
        self.label_14 = QtWidgets.QLabel(self.outputFrame)
        self.label_14.setGeometry(QtCore.QRect(10, 7, 56, 20))
        self.label_14.setObjectName("label_14")
        Cgtriangle.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Cgtriangle)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        Cgtriangle.setMenuBar(self.menubar)
        self.actionClear = QtWidgets.QAction(Cgtriangle)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon3)
        self.actionClear.setObjectName("actionClear")
        self.actionOpen_file = QtWidgets.QAction(Cgtriangle)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_file.setIcon(icon4)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave = QtWidgets.QAction(Cgtriangle)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(Cgtriangle)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.actionGithub_repository = QtWidgets.QAction(Cgtriangle)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGithub_repository.setIcon(icon7)
        self.actionGithub_repository.setObjectName("actionGithub_repository")
        self.actionAbout_this_software = QtWidgets.QAction(Cgtriangle)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/doc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_this_software.setIcon(icon8)
        self.actionAbout_this_software.setObjectName("actionAbout_this_software")
        self.actionCompile = QtWidgets.QAction(Cgtriangle)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompile.setIcon(icon9)
        self.actionCompile.setObjectName("actionCompile")
        self.actionUpdate = QtWidgets.QAction(Cgtriangle)
        self.actionUpdate.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate.setIcon(icon10)
        self.actionUpdate.setObjectName("actionUpdate")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionGithub_repository)
        self.menuHelp.addAction(self.actionAbout_this_software)
        self.menuTools.addAction(self.actionCompile)
        self.menuTools.addAction(self.actionUpdate)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Cgtriangle)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Cgtriangle)

    def retranslateUi(self, Cgtriangle):
        _translate = QtCore.QCoreApplication.translate
        Cgtriangle.setWindowTitle(_translate("Cgtriangle", "CG-Triangle"))
        self.pushVertice.setText(_translate("Cgtriangle", " Push"))
        self.pushVertice.setShortcut(_translate("Cgtriangle", "F2, Space"))
        self.popVertice.setText(_translate("Cgtriangle", " Pop"))
        self.popVertice.setShortcut(_translate("Cgtriangle", "Del"))
        self.helpText.setHtml(_translate("Cgtriangle", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You must insert at least <span style=\" font-weight:600;\">3 vertices</span> through the \'<span style=\" font-weight:600;\">push</span>\' button. After this, you can render your polygon clicking in <span style=\" font-weight:600;\">Tools &gt; Render</span>, or pressing <span style=\" font-weight:600;\">F4 key</span> shortcut. </p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">If you need help, go to the </span><span style=\" font-weight:600; font-style:italic;\">Help &gt; Github repository</span><span style=\" font-style:italic;\"> to read the documentation.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vertices), _translate("Cgtriangle", "Polygon Vertices"))
        self.boxTranslation.setTitle(_translate("Cgtriangle", "Translation"))
        self.label.setText(_translate("Cgtriangle", "Tx:"))
        self.label_2.setText(_translate("Cgtriangle", "Ty:"))
        self.boxScale.setTitle(_translate("Cgtriangle", "Scale"))
        self.label_3.setText(_translate("Cgtriangle", "Sx:"))
        self.label_4.setText(_translate("Cgtriangle", "Sy:"))
        self.label_5.setText(_translate("Cgtriangle", "Vertices:"))
        self.boxShearing.setTitle(_translate("Cgtriangle", "Shear"))
        self.label_6.setText(_translate("Cgtriangle", "Cx:"))
        self.label_7.setText(_translate("Cgtriangle", "Cy:"))
        self.boxRotation.setTitle(_translate("Cgtriangle", "Rotation"))
        self.label_10.setText(_translate("Cgtriangle", "Angle:"))
        self.label_12.setText(_translate("Cgtriangle", "Vertices:"))
        self.label_13.setText(_translate("Cgtriangle", "Direction:"))
        self.boxReflection.setTitle(_translate("Cgtriangle", "Reflection"))
        self.reflection_x.setText(_translate("Cgtriangle", "X"))
        self.reflection_y.setText(_translate("Cgtriangle", "Y"))
        self.label_11.setText(_translate("Cgtriangle", "Axes:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_transformations), _translate("Cgtriangle", "2D Transformations"))
        self.label_14.setText(_translate("Cgtriangle", "output:"))
        self.menuFile.setTitle(_translate("Cgtriangle", "File"))
        self.menuHelp.setTitle(_translate("Cgtriangle", "Help"))
        self.menuTools.setTitle(_translate("Cgtriangle", "Tools"))
        self.actionClear.setText(_translate("Cgtriangle", "Clear data"))
        self.actionClear.setToolTip(_translate("Cgtriangle", "Clears all entered data"))
        self.actionClear.setShortcut(_translate("Cgtriangle", "Ctrl+N"))
        self.actionOpen_file.setText(_translate("Cgtriangle", "Open file"))
        self.actionOpen_file.setShortcut(_translate("Cgtriangle", "Ctrl+O"))
        self.actionSave.setText(_translate("Cgtriangle", "Save"))
        self.actionSave.setShortcut(_translate("Cgtriangle", "Ctrl+S"))
        self.actionExit.setText(_translate("Cgtriangle", "Exit"))
        self.actionGithub_repository.setText(_translate("Cgtriangle", "Github repository"))
        self.actionAbout_this_software.setText(_translate("Cgtriangle", "About"))
        self.actionAbout_this_software.setShortcut(_translate("Cgtriangle", "F1"))
        self.actionCompile.setText(_translate("Cgtriangle", "Render"))
        self.actionCompile.setShortcut(_translate("Cgtriangle", "F4"))
        self.actionUpdate.setText(_translate("Cgtriangle", "Update"))
        self.actionUpdate.setShortcut(_translate("Cgtriangle", "F5"))

